nodes = [
    {'source': 'Resham Chaudhary', 'target': 'fake Bhutanese refugee scam', 'label': 'involved in'},
    {'source': 'Resham', 'target': 'fake Bhutanese refugee scam', 'label': 'involved in'},
    {'source': 'Chaudhary', 'target': 'fake Bhutanese refugee scam', 'label': 'involved in'},
    {'source': 'Tek Nath Rizal', 'target': 'fake Bhutanese refugee scam', 'label': 'involved in'},
    {'source': 'Vulture Theatre', 'target': 'Nepal', 'label': 'misunderstood in'},
    {'source': 'Poco F5 Pro', 'target': 'a rebranding, remarkable release', 'label': 'despite being'},
    {'source': 'Nepal PM Dahal', 'target': 'India from May 31 to June 3', 'label': 'to visit'},
    {'source': 'Nepal PM Dahal', 'target': 'India from May 31 to June 3', 'label': 'to visit'},
    {'source': 'Supreme Court', 'target': 'Bindabasini Kansakar to replace Dhaka Kumar Shrestha', 'label': 'clears the decks for'},
    {'source': 'National Assembly', 'target': 'annual policy and programme', 'label': 'endorses'},
    {'source': 'Dahal cabinet', 'target': 'one minister, one state minister inducted', 'label': 'gets full shape with'},
    {'source': 'Dahal', 'target': 'one minister, one state minister inducted', 'label': 'cabinet gets full shape with'},
    {'source': 'Girl', 'target': 'Khandbari', 'label': 'hacked to death in'},
    {'source': 'Man', 'target': 'Rautahat', 'label': 'shot dead in'},
    {'source': 'Bagmati province', 'target': '3,000 old vehicles amid entrepreneurs\' protest', 'label': 'removing over'},
    {'source': 'Bagmati', 'target': '3,000 old vehicles amid entrepreneurs\' protest', 'label': 'removing over'},
    {'source': 'Gautam Buddha International Airport', 'target': '', 'label': 'revenue collection low at'},
    {'source': 'MDMS system', 'target': "5 million phones in Nepal 'illegal' amid concerns over data security of legal phones", 'label': 'renders'},
    {'source': 'Smoking', 'target': 'public places, warns of action in case of rule breach', 'label': 'banned in'},
    {'source': 'Gary Wornell', 'target': 'Nepali crafts', 'label': 'dedicated his life to promoting'},
    {'source': 'Hydrafacial in Nepal', 'target': '', 'label': ''},
    {'source': 'Nepal Airlines', 'target': 'Kathmandu-Sydney flights via Singapore', 'label': 'preparing for'},
    {'source': 'Ponds in Bhaktapur', 'target': '', 'label': 'your next rest stop, a breath of fresh air'},
    {'source': 'Bhaktapur', 'target': '', 'label': 'your next rest stop, a breath of fresh air'},
    {'source': 'Ponds', 'target': '', 'label': 'in bhaktapur your next rest stop, a breath of fresh air'},
    {'source': 'Kami Rita Sherpa', 'target': 'Everest 28th time, leaving Pasang Dawa Sherpa behind the record', 'label': 'climbs'},
    {'source': 'Kami', 'target': 'Everest 28th time, leaving Pasang Dawa Sherpa behind the record', 'label': ' Rita Sherpa climbs'},
    {'source': 'Ripples of Thirst', 'target': 'Kathmandu\'s ancient hiti system awaits revival', 'label': ''},
    {'source': 'Bhoto Dekhaune Jatra', 'target': 'the Kathmandu valley on Thursday', 'label': 'public holiday in'},
    {'source': 'Dabali', 'target': 'sustainable planning in traditional architecture in Kathmandu', 'label': 'an example of'},
    {'source': 'Vipassana in Nepal', 'target': '', 'label': 'Know why international celebrities come to the country for meditation'},
    {'source': 'Grassroots groups', 'target': 'human-wildlife conflict across the India-Nepal border', 'label': 'tackle'},
    {'source': 'Bajhang avalanche', 'target': '', 'label': '1 dead, 2 missing'},
    {'source': 'Nepal biodiversity', 'target': '', 'label': '9 flora and fauna species found almost exclusively in the region'},
    {'source': 'ICC World Cup Qualifiers', 'target': '', 'label': 'CAN deems no warm-up against test nations unfair'},
    {'source': 'ICC Qualifiers', 'target': '', 'label': 'CAN deems no warm-up against test nations unfair'},
    {'source': 'World Cup', 'target': '', 'label': 'Qualifiers CAN deems no warm-up against test nations unfair'},
    {'source': 'ANFA', 'target': 'U23 Asian Cup Qualifiers citing lack of funds', 'label': 'pulls out of'},
    {'source': "CAVA Women's Volleyball", 'target': '', 'label': 'Nepal, India reach semis, to play for top spot tomorrow'},
    {'source': "CAVA", 'target': '', 'label': 'Nepal, India reach semis, to play for top spot tomorrow'},
    {'source': "Women's Volleyball", 'target': '', 'label': 'Nepal, India reach semis, to play for top spot tomorrow'},
    {'source': 'Monkey Temple', 'target': '8 songs from Nepal\'s pioneering alternative rock band you shouldn\'t miss', 'label': ''},
    {'source': 'Nepal', 'target': 'electricity from petroleum', 'label': 'preparing to shift to'}
]

label_templates = {
    'involved in': "The source is involved in {target}.",
    'misunderstood in': "The source is misunderstood in {target}.",
    'despite being': "Despite being {target}, the source is a {source}.",
    'to visit': "The source plans to visit {target} from {start_date} to {end_date}.",
    'clears the decks for': "The Supreme Court clears the decks for {target} by replacing {source} with {target}.",
    'endorses': "The National Assembly endorses the {target} for the year.",
    'gets full shape with': "The Dahal cabinet gets full shape with one minister and one state minister being inducted.",
    'hacked to death in': "A girl was hacked to death in {target}.",
    'shot dead in': "A man was shot dead in {target}.",
    'removing over': "The Bagmati province is removing over 3,000 old vehicles amid entrepreneurs' protest.",
    'revenue collection low at': "The revenue collection is low at {target}.",
    'renders': "The MDMS system renders {target} illegal amid concerns over data security.",
    'banned in': "Smoking is banned in {target}.",
    'dedicated his life to promoting': "Gary Wornell has dedicated his life to promoting {target}.",
    'preparing for': "Nepal Airlines is preparing for Kathmandu-Sydney flights via Singapore.",
    'your next rest stop, a breath of fresh air': "The ponds in Bhaktapur are your next rest stop, a breath of fresh air.",
    'climbs': "Kami Rita Sherpa climbs Everest for the 28th time, leaving Pasang Dawa Sherpa behind the record.",
    'an example of': "Dabali is an example of sustainable planning in traditional architecture in Kathmandu.",
    'Know why international celebrities come to the country for meditation': "Vipassana in Nepal: Know why international celebrities come to the country for meditation.",
    'tackle': "Grassroots groups tackle human-wildlife conflict across the India-Nepal border.",
    '1 dead, 2 missing': "There was an avalanche in Bajhang resulting in 1 dead and 2 missing.",
    '9 flora and fauna species found almost exclusively in the region': "Nepal biodiversity: 9 flora and fauna species found almost exclusively in the region.",
    'CAN deems no warm-up against test nations unfair': "The ICC World Cup Qualifiers: CAN deems no warm-up against test nations unfair.",
    'pulls out of': "ANFA pulls out of U23 Asian Cup Qualifiers citing lack of funds.",
    'Nepal, India reach semis, to play for top spot tomorrow': "In CAVA Women's Volleyball, Nepal and India reach semis and will play for the top spot tomorrow.",
    '8 songs from Nepal\'s pioneering alternative rock band you shouldn\'t miss': "Monkey Temple: 8 songs from Nepal's pioneering alternative rock band you shouldn't miss.",
    'preparing to shift to': "Nepal is preparing to shift from electricity to petroleum."
}
